version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.0
    - 5.22.0
    - 5.26.0
    - 5.26.1
    - 5.27.0
    - 5.27.1
    - 5.32.0
    - 5.33.2
    - 5.35.0
  - dependency-name: whatwg-fetch
    versions:
    - 3.6.0
