name: build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    name: Node ${{ matrix.node }} run
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install npm modules
        run: npm install
      - name: Apt Update
        run: sudo apt-get -qq update
      - name: Install libgif-dev
        run: sudo apt-get install -y libgif-dev
      - name: Run eslint
        run: make eslint
      - name: Test
        run: make test
